# Generated by Django 5.1.6 on 2026-02-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_desc', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(blank=True, help_text='Tags separados por coma', max_length=300)),
                ('url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='detailed_info',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG inline o emoji'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible para proyectos'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_title',
            field=models.CharField(default='Oscar Javier', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(default='Data Engineer & Cloud Solutions', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=80),
        ),
    ]
