# Generated by Django 5.1.6 on 2026-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_remove_service_detailed_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la certificación')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Organización emisora')),
                ('issue_date', models.DateField(verbose_name='Fecha de emisión')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID de la credencial')),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de la credencial')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Imagen/Badge')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['order', '-issue_date'],
            },
        ),
    ]
