# Generated by Django 5.1.6 on 2026-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, help_text='Qué cubre la certificación, habilidades validadas, etc.', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Dejar en blanco si no vence', null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, verbose_name='URL de verificación'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Imagen / Badge'),
        ),
    ]
