# Generated by Django 5.1.6 on 2026-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certification_add_description_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('data', 'Data Engineering'), ('automation', 'Automatización n8n'), ('other', 'Otro')], default='data', max_length=20, verbose_name='Tipo de proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Video demo del proyecto (mp4, webm — máx 50 MB)', null=True, upload_to='projects/videos/'),
        ),
    ]
