# Generated by Django 5.1.6 on 2026-03-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_project_type_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='profile_image_static',
            field=models.CharField(blank=True, help_text="Ruta dentro de static/ (ej: img/avatar.webp). Tiene prioridad sobre 'profile_image' para producción.", max_length=200),
        ),
    ]
