# Generated by Django 5.1.6 on 2026-03-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_profile_image_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='clippy_default_message',
            field=models.CharField(default='¿En qué puedo ayudarte hoy?', help_text='Mensaje cuando no hay sección específica detectada', max_length=300, verbose_name='Mensaje por defecto'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='clippy_delay_desktop',
            field=models.IntegerField(default=30, help_text='Segundos antes de que aparezca en escritorio', verbose_name='Delay desktop (seg)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='clippy_delay_mobile',
            field=models.IntegerField(default=20, help_text='Segundos antes de que aparezca en móvil', verbose_name='Delay mobile (seg)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='clippy_enabled',
            field=models.BooleanField(default=True, help_text='Activa o desactiva el asistente inteligente flotante', verbose_name='Widget Clippy activo'),
        ),
    ]
